Update to use Ubuntu 22.04
This solves the issue where this error is produced during building. This error also occurs in 20.04.

ERROR:  Error installing jekyll:
The last version of sass-embedded (~> 1.54) to support your Ruby & RubyGems was 1.58.3. Try installing it with `gem install sass-embedded -v 1.58.3` and then running the current command again
sass-embedded requires RubyGems version >= 3.3.22. The current RubyGems version is 3.1.2. Try 'gem update --system' to update RubyGems itself.